- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "Other Locations/Computer/var/snap/jenkins/4865/workspace/MyMavenWebAnsible-CICD-Pipeline/target/MyMavenWebAnsible.war"
        dest: "/opt/tomcat/webapps/MyMavenWebAnsible.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
